package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/davenicholson-xyz/rewind/app"
	"github.com/spf13/cobra"
)

const RewindDirName = ".rewind"
const EnvrcFileName = ".envrc"
const IgnoreFileName = ".rwignore"

var initCmd = &cobra.Command{
	Use:   "init [directory]",
	Short: "Initialize a new rewind project",
	Long: `Initialize a new rewind project in the specified directory or current directory.

This command creates a .rewind directory and sets up the necessary configuration files
for file watching and version control. If no directory is specified, the current
directory will be used.

Examples:
  rewind init
  rewind init .
  rewind init /path/to/project
  rewind init my-project`,
	Run: runInit,
}

var createEnvrc bool
var createIgnore bool

func init() {
	rootCmd.AddCommand(initCmd)
	initCmd.Flags().BoolVarP(&createEnvrc, "envrc", "e", false, "Generate .envrc file")
	initCmd.Flags().BoolVarP(&createIgnore, "ignore", "i", false, "Generate ignore file")
}

func runInit(cmd *cobra.Command, args []string) {

	app.Logger.Info("Starting new rewind app")

	targetDir, err := determineTargetDirectory(args)
	app.Logger.WithField("directory", targetDir).Debug("Target directory")
	if err != nil {
		fmt.Printf("Error: %v\n", err)
		os.Exit(1)
	}

	if err := validateDirectory(targetDir); err != nil {
		fmt.Printf("Error: %v\n", err)
		os.Exit(1)
	}

	absTargetDir, err := filepath.Abs(targetDir)
	app.Logger.WithField("abs_directory", absTargetDir).Debug("Absolute target directory")
	if err != nil {
		fmt.Printf("Error getting absolute path: %v\n", err)
		os.Exit(1)
	}

	if err := checkExistingRewind(absTargetDir); err != nil {
		app.Logger.Error("Already inside rewind project")
		fmt.Printf("Error: %v\n", err)
		os.Exit(1)
	}

	if err := initializeRewindProject(absTargetDir); err != nil {
		fmt.Printf("Error: %v\n", err)
		os.Exit(1)
	}

	runWatcher()
}

func determineTargetDirectory(args []string) (string, error) {
	if len(args) == 0 || args[0] == "." {
		return os.Getwd()
	}
	return args[0], nil
}

func validateDirectory(dir string) error {
	if _, err := os.Stat(dir); os.IsNotExist(err) {
		return fmt.Errorf("target directory does not exist: %s", dir)
	}
	return nil
}

func checkExistingRewind(absTargetDir string) error {
	rewindDir := filepath.Join(absTargetDir, ".rewind")
	if _, err := os.Stat(rewindDir); err == nil {
		return fmt.Errorf("rewind already initialized in this directory")
	}

	if hasRewindInParents(absTargetDir) {
		return fmt.Errorf("already inside a rewind project")
	}

	return nil
}

func initializeRewindProject(absTargetDir string) error {
	rewindDir := filepath.Join(absTargetDir, RewindDirName)

	if err := createRewindDirectory(rewindDir); err != nil {
		return fmt.Errorf("unable to create .rewind directory: %w", err)
	}
	app.Logger.WithField("dir", rewindDir).Info("Created .rewind directory")

	if createEnvrc {
		if err := createEnvrcFile(absTargetDir); err != nil {
			return fmt.Errorf("unable to create .envrc file: %w", err)
		}
		app.Logger.WithField("dir", filepath.Join(absTargetDir, EnvrcFileName)).Info("Created .envrc file")
	}

	if createIgnore {
		if err := createIgnoreFile(absTargetDir); err != nil {
			return fmt.Errorf("unable to create .rwignore file: %w", err)
		}
		app.Logger.WithField("dir", filepath.Join(absTargetDir, IgnoreFileName)).Info("Created .rwignore file")
	}

	dbm, err := app.NewDatabaseManager(absTargetDir)
	if err != nil {
		return fmt.Errorf("unable to create db manager: %w", err)
	}

	if err := dbm.InitDatabase(); err != nil {
		return fmt.Errorf("unable to initialize database: %w", err)
	}

	return nil
}

func hasRewindInParents(dir string) bool {
	currentDir := filepath.Dir(dir)

	for currentDir != filepath.Dir(currentDir) {
		rewindPath := filepath.Join(currentDir, RewindDirName)
		if _, err := os.Stat(rewindPath); err == nil {
			return true
		}
		currentDir = filepath.Dir(currentDir)
	}

	return false
}

func createEnvrcFile(dir string) error {
	envrcFile := filepath.Join(dir, EnvrcFileName)
	if _, err := os.Stat(envrcFile); err == nil {
		return nil // File already exists, skip creation
	}

	envrcContent := `# Auto-generated by rewind
if command -v rewind >/dev/null 2>&1; then
    rewind watch >/dev/null 2>&1 &
    export REWIND_PID=$!
fi`

	return os.WriteFile(envrcFile, []byte(envrcContent), 0644)
}

func createIgnoreFile(dir string) error {
	ignoreFile := filepath.Join(dir, IgnoreFileName)
	if _, err := os.Stat(ignoreFile); err == nil {
		return nil
	}

	ignoreContent := `# Auto-generated by rewind
`

	return os.WriteFile(ignoreFile, []byte(ignoreContent), 0644)
}

func createRewindDirectory(dir string) error {
	if err := os.Mkdir(dir, 0755); err != nil {
		return err
	}

	ignoreContent := `# Auto-generated by rewind
.git
.git/*
node_modules
node_modules/*
.DS_Store
*.tmp
*.log
.rewind
.rewind/
.rwignore
*~
*.swp
*.swo
.*.swp
.*.swo
#*#
.#*
*.tmp
*.*~
.vscode/*
`

	ignoreFile := filepath.Join(dir, "ignore")
	return os.WriteFile(ignoreFile, []byte(ignoreContent), 0644)
}
